### PR TITLE
Use V8's API if exists.

### PR DESCRIPTION
**Pull request by Xotic750**
Sorry couldn't test locally because PhantomJS wouldn't run on my machine for some reason.

### CODE REVIEW

**Comment by Xotic750** [comment]
And seems the tests won't run from a PR either due to credentials.

**Comment by eriwen** [comment]
Thanks for the PR, @Xotic750. All tests pass except for on Chrome, where all fail. Could you change line 26 of karma.conf.js to `'Chrome'` and take a look? I think this is because Chrome stacks somehow only contain entries for `error-stack-parser-spec.js` and Jasmine-related JS files instead of the functions we expect. 

Example failure:
```
Chrome 46.0.2490 (Linux 0.0.0): Executed 6 of 15 (6 FAILED) (0 secs / 0.015 secs)
Chrome 46.0.2490 (Linux 0.0.0) ErrorStackParser #parse should parse V8 Error.stack FAILED
	Expected 10 to be 4.
	Error: Expected 10 to be 4.
	    at null.<anonymous> (/Users/ewendelin/src/stacktracejs/error-stack-parser/spec/error-stack-parser-spec.js:49:40)
	expected functionName: null to equal bar
	expected fileName: /Users/ewendelin/src/stacktracejs/error-stack-parser/spec/error-stack-parser-spec.js to equal http://path/to/file.js
	expected lineNumber: 47 to equal 13
	expected columnNumber: 36 to equal 17

	Error: expected functionName: null to equal bar
	expected fileName: /Users/ewendelin/src/stacktracejs/error-stack-parser/spec/error-stack-parser-spec.js to equal http://path/to/file.js
	expected lineNumber: 47 to equal 13
	expected columnNumber: 36 to equal 17

	    at null.<anonymous> (/Users/ewendelin/src/stacktracejs/error-stack-parser/spec/error-stack-parser-spec.js:50:36)
	expected functionName: jasmine.Block.execute to equal bar
	expected fileName: /Users/ewendelin/src/stacktracejs/error-stack-parser/node_modules/karma-jasmine/lib/jasmine.js to equal http://path/to/file.js
	expected lineNumber: 1145 to equal 16
	expected columnNumber: 17 to equal 5

	Error: expected functionName: jasmine.Block.execute to equal bar
	expected fileName: /Users/ewendelin/src/stacktracejs/error-stack-parser/node_modules/karma-jasmine/lib/jasmine.js to equal http://path/to/file.js
	expected lineNumber: 1145 to equal 16
	expected columnNumber: 17 to equal 5

	    at null.<anonymous> (/Users/ewendelin/src/stacktracejs/error-stack-parser/spec/error-stack-parser-spec.js:51:36)
	expected functionName: jasmine.Queue.next_ to equal foo
	expected fileName: /Users/ewendelin/src/stacktracejs/error-stack-parser/node_modules/karma-jasmine/lib/jasmine.js to equal http://path/to/file.js
	expected lineNumber: 2177 to equal 20
	expected columnNumber: 31 to equal 5

	Error: expected functionName: jasmine.Queue.next_ to equal foo
	expected fileName: /Users/ewendelin/src/stacktracejs/error-stack-parser/node_modules/karma-jasmine/lib/jasmine.js to equal http://path/to/file.js
	expected lineNumber: 2177 to equal 20
	expected columnNumber: 31 to equal 5

	    at null.<anonymous> (/Users/ewendelin/src/stacktracejs/error-stack-parser/spec/error-stack-parser-spec.js:52:36)
	expected functionName: jasmine.Queue.start to equal undefined
	expected fileName: /Users/ewendelin/src/stacktracejs/error-stack-parser/node_modules/karma-jasmine/lib/jasmine.js to equal http://path/to/file.js
	expected lineNumber: 2130 to equal 24
	expected columnNumber: 8 to equal 4

	Error: expected functionName: jasmine.Queue.start to equal undefined
	expected fileName: /Users/ewendelin/src/stacktracejs/error-stack-parser/node_modules/karma-jasmine/lib/jasmine.js to equal http://path/to/file.js
	expected lineNumber: 2130 to equal 24
	expected columnNumber: 8 to equal 4
```

**Comment by Xotic750** [comment]
Changed `conf` as suggested and ran locally, can see the failures. It looks like the API reports the details of where the `throw` occurred rather than where `new Error` was called. Not sure if that can be fixed, or is even a real problem? :/

I think this demonstrates it.
http://jsfiddle.net/zvbcb1mk/3/

**Comment by eriwen** [comment]
I really like this idea, so I hope we can make it work. 

The only thing I wonder about regarding the test failures is why we don't get any lines from the original source. Sounds like you're on the same page here; let us know if we can help :)

**Comment by Xotic750** [comment]
Well, I have tried a number of different things and I can#t get the same values when using the API compared to parsing the string. It just seems to have a slightly different behaviour compared to the default. Maybe there is someone out there that knows and has dealt with it before, but just now this is beyond me.

https://chromium.googlesource.com/v8/v8/+/master/docs/javascript_stack_trace_api.md

**Comment by Xotic750** [comment]
On the off chance you are interested in how this was used, and how your module is used, here is the project link https://github.com/Xotic750/error-x

**Comment by eriwen** [comment]
@Xotic750 Already starred it :) 

I took an initial look - seems useful for Error reporting. 

Let us know if there is any way we can improve his library in order to support your project.

**Comment by eriwen** [comment]
Seems like you got all of this working for your own project, so I'm going to close this PR. 

Please re-open if we can use V8-specific APIs in this project.

**Pull request closed without merging**
